useDefaultWorkingPath: true
workingPath: 
workshop:
  publishedID: 3620106581
  visibility: Private
  textFromMetadataVersion: true
  textFromMetadataMain: true
  title: 
  description: 
  internalData: 
  changes: Updated Portrait for 2.0
  tags:
  - Pilots
  texPreviewUpload: true
configEdits: 
textEdits: 
assetBundles: 
libraryDLLs: 
extraFiles: 
